config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "homes#top"

  resources :articles, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/users/:id/quit' => 'users#quit', as: 'quit'
  patch '/users/:id/out' => 'users#out', as: 'out'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :comment, presence: true
end

app/controllers/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    comment = ArticleComment.new(article_comment_params)
    comment.user_id = current_user.id
    comment.article_id = @article.id
    if !comment.save
      @error_comment = comment
      render :error
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    ArticleComment.find(params[:id]).destroy
  end

  private

  def article_comment_params
    params.require(:article_comment).permit(:comment)
  end
end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/views/article_comments/_counter.html.erb
<%= link_to article_path(article.id), class: "text-dark" do %>
    <i class="far fa-comment"></i> <%= article.article_comments.count %>
<% end %>

app/views/article_comments/_counter_comment.html.erb
<h4><%= @article.article_comments.count %>件コメント</h4>

app/views/article_comments/_error.html.erb
<% if error_comment.present? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= error_comment.errors.count %>件のエラーが発生しました
    </h6>
    <% error_comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/article_comments/_form.html.erb
<div>
  <div class="comments-error">
    <%= render 'article_comments/error', error_comment: @error_comment %>
  </div>
  <%= form_with model: [article, article_comment], local:false do |f| %>
    <%= f.text_area :comment, class: "form-control", row: '5', placeholder: "コメントをここに", class: 'comment-textarea' %>
    <%= f.submit "送信する", class: "btn btn-info m-2 " %>
  <% end %>
</div>

app/views/article_comments/_index.html.erb
<% article.article_comments.each do |article_comment| %>
  <div class="row d-flex flex-column mt-2">
    <div>
      <%= image_tag article_comment.user.get_profile_image(50,50), class: "rounded-circle border"; %>
      <%= link_to user_path(article_comment.user), class: "text-dark" do %>
        <%= article_comment.user.name %>
      <% end %>
    </div>
    <div class="pl-2">
      <%= article_comment.comment %><br>
      <%= article_comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
      <% if article_comment.user == current_user %>
        <%= link_to article_article_comment_path(article_comment.article,article_comment), method: :delete, class: "btn btn-danger", remote: true do %>
          <i class="fas fa-trash"></i>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/article_comments/create.js.erb
$('.comment-textarea').val("")
$('.article-comments-counter').html("<%= j(render 'article_comments/counter', article: @article) %>")
$('.article-comment-counter').html("<%= j(render 'article_comments/counter_comment', article: @article) %>")
$('.article-comments-index').html("<%= j(render 'article_comments/index', article: @article) %>")

app/views/article_comments/destroy.js.erb
$('.article-comments-counter').html("<%= j(render 'article_comments/counter', article: @article) %>")
$('.article-comment-counter').html("<%= j(render 'article_comments/counter_comment', article: @article) %>")
$('.article-comments-index').html("<%= j(render 'article_comments/index', article: @article) %>")

app/views/article_comments/error.js.erb
$('.comments-error').html("<%= j(render 'article_comments/error', error_comment: @error_comment) %>")