config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "homes#top"

  resources :articles, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/users/:id/quit' => 'users#quit', as: 'quit'
  patch '/users/:id/out' => 'users#out', as: 'out'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def index
    @articles = Article.page(params[:page]).order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
    @article_comment = ArticleComment.new
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def search
    @results = @q.result.page(params[:page])
  end

  private

  def set_q
    @q = Article.ransack(params[:q])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_list.html.erb
  <% articles.each do |article| %>
  <div class="container border w-50 mx-auto mt-4">
    <div class="row border-bottom d-flex align-items-center">
      <p class="pr-2 pt-2"><%= image_tag article.user.get_profile_image(50,50), class: "rounded-circle border"; %></p>
      <%= link_to user_path(article.user), class: "text-dark" do %>
        <h3><%= article.user.name %></h3>
      <% end %>
    </div>
    <div class="row border-bottom pl-2">
      <p class="lead"><i class="fas fa-gamepad"></i>  <%= article.title %></p>
    </div>
    <div class="row pl-2">
      <%= link_to article_path(article.id), class: "text-dark" do %>
        <p class="lead"><%= article.body %></p>
      <% end %>
    </div>
    <div class="row">
      <div class="col-3" id="favorite_buttons_<%= article.id %>">
        <%= render 'favorites/btn', article: article %>
      </div>
      <div class="col-3">
        <%= render 'article_comments/counter', article: article %>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate articles %>

app/views/articles/index.html.erb
<div class="container mx-auto">
  <h1 class="text-center mt-4">投稿一覧</h1>
  <div class="row justify-content-center">
    <%= search_form_for @q, url: search_articles_path do |f| %>
    <%= f.search_field :title_cont, placeholder: "ゲームタイトル" %>
      <%= button_tag :type => "submit", :class =>"btn btn-secondary" do %>
        <i class="fa fa-search"></i>
      <% end %>
  <% end %>
  </div>

  <%= render 'list', articles: @articles %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">新規投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @article.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @article.errors.count %>件のエラーが発生しました
            </h6>
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @article do |f| %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-gamepad"></i></span>
            </div>
            <%= f.text_field :title, class: "form-control", placeholder: "ゲームタイトル" %>
          </div>
          <%= f.text_area :body, class: "form-control", rows: "3", placeholder: "コメントここに"  %>
          <hr>
          <%= f.submit '投稿', class: "btn btn-lg btn-info btn-block mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/search.html.erb
<div class="container mx-auto">
  <h1 class="text-center mt-4">検索結果</h1>

  <%= render 'list', articles: @results %>
</div>

app/views/articles/show.html.erb
<div class="container border w-50 mx-auto mt-4 mb-4">
  <div class="row border-bottom d-flex align-items-center">
    <p class="pr-2 pt-2"><%= image_tag @article.user.get_profile_image(50,50), class: "rounded-circle border"; %></p>
    <%= link_to user_path(@article.user), class: "text-dark" do %>
      <h3><%= @article.user.name %></h3>
    <% end %>
  </div>
  <div class="row border-bottom pl-2">
    <p class="lead"><i class="fas fa-gamepad"></i> <%= @article.title %></p>
  </div>
  <div class="row pl-2">
      <p class="lead"><%= @article.body %></p>
  </div>
  <div class="row">
    <div class="col-3" id="favorite_buttons_<%= @article.id %>">
      <%= render 'favorites/btn', article: @article %>
    </div>
    <div class="col-3 article-comments-counter">
      <%= render 'article_comments/counter', article: @article %>
    </div>

  </div>
  <div class="row border-bottom pl-2">
    <p><%= @article.created_at.strftime('%Y/%m/%d %H:%M:%S') %></p>
    <p>
      <% if @article.user == current_user %>
        <%= link_to article_path(@article), method: :delete, class: "btn btn-danger" do %>
          <i class="fas fa-trash"></i>
        <% end %>
      <% end %>
    </p>
  </div>
  <div class="row border-bottom pl-2 mb-2 article-comment-counter">
    <%= render 'article_comments/counter_comment', article: @article %>
  </div>
  <div class="article-comments-index">
    <%= render 'article_comments/index', article: @article %>
  </div>
  <div class="article-comments-form">
    <%= render 'article_comments/form', article: @article, article_comment: @article_comment %>
  </div>
</div>