config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: "homes#top"

  resources :articles, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  get '/users/:id/quit' => 'users#quit', as: 'quit'
  patch '/users/:id/out' => 'users#out', as: 'out'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/_follow_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50), class: "rounded-circle border"; %></td>
        <td>
          <%= link_to user_path(user), class: "text-dark" do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= render "relationships/btn", user: user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/relationships/followers.html.erb
<div class="container w-50 mx-auto">
  <h2 class="text-center pt-2">フォロワー</h2>
  <% if @users.exists? %>
    <%= render 'follow_list', users: @users %>
  <% else %>
    <p class="text-center">ユーザーはいません</p>
  <% end %>
</div>

app/views/relationships/followings.html.erb
<div class="container w-50 mx-auto">
  <h2 class="text-center pt-2">フォロー中</h2>
  <% if @users.exists? %>
    <%= render 'follow_list', users: @users %>
  <% else %>
    <p class="text-center">ユーザーはいません</p>
  <% end %>
</div>